# Generated by Django 5.0.2 on 2024-02-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueModel',
            fields=[
                ('league_id', models.IntegerField(db_index=True, max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='Id по api')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('logo', models.URLField(verbose_name='Лого')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.countrymodel', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
            },
        ),
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('start_date', models.DateTimeField(verbose_name='Начало')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('current', models.BooleanField(verbose_name='Текущий')),
                ('events', models.BooleanField(verbose_name='События')),
                ('lineups', models.BooleanField()),
                ('statistics_fixtures', models.BooleanField()),
                ('statistics_players', models.BooleanField()),
                ('standings', models.BooleanField()),
                ('players', models.BooleanField()),
                ('top_scorers', models.BooleanField()),
                ('top_assists', models.BooleanField()),
                ('top_cards', models.BooleanField()),
                ('injuries', models.BooleanField()),
                ('predictions', models.BooleanField()),
                ('odds', models.BooleanField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.leaguemodel', verbose_name='Лига')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
    ]
