# Generated by Django 5.0.2 on 2024-02-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_leaguemodel_seasonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguemodel',
            name='league_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Id по api'),
        ),
    ]
