# Generated by Django 5.0.2 on 2024-02-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_leaguemodel_league_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('team_id', models.IntegerField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id по api')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('national', models.BooleanField()),
                ('logo', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.countrymodel', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(blank=True, max_length=255, null=True)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
                ('seconds', models.CharField(blank=True, max_length=10, null=True)),
                ('home_goals', models.IntegerField(blank=True, null=True, verbose_name='Гол (Дома)')),
                ('away_goals', models.IntegerField(blank=True, null=True, verbose_name='Гол (Гости)')),
                ('stopped', models.BooleanField()),
                ('blocked', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('update', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.leaguemodel', verbose_name='Лига')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='sport.teammodel', verbose_name='Гости')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='sport.teammodel', verbose_name='Дома')),
            ],
        ),
    ]
