# Generated by Django 5.0.2 on 2024-02-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_teammodel_gamemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='game_id',
            field=models.IntegerField(db_index=True, default=1, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='slug',
            field=models.SlugField(default='123', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
