# Generated by Django 5.0.2 on 2024-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_remove_gamemodel_id_gamemodel_game_id_gamemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='leaguemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
