# Generated by Django 5.0.2 on 2024-02-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_toplistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='sport.leaguemodel', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='toplistmodel',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_top', to='sport.leaguemodel'),
        ),
    ]
