# Generated by Django 5.0.2 on 2024-02-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_gamemodel_game_date_alter_gamemodel_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='sport.teammodel', verbose_name='Победители'),
        ),
    ]
