# Generated by Django 5.0.2 on 2024-02-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_gamemodel_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainColumnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('main_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='sport.maincolumnmodel')),
            ],
        ),
    ]
