# Generated by Django 5.0.2 on 2024-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0011_alter_columnmodel_url_alter_maincolumnmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmodel',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
