# Generated by Django 5.0.2 on 2024-02-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_countrymodel_flag_alter_countrymodel_code_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymodel',
            old_name='code_country',
            new_name='code',
        ),
    ]
