# Generated by Django 5.0.2 on 2024-02-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0017_alter_countrymodel_name_alter_leaguemodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonmodel',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='seasonmodel',
            old_name='start_date',
            new_name='start',
        ),
    ]
