# Generated by Django 5.0.2 on 2024-02-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0018_rename_end_date_seasonmodel_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemodel',
            old_name='game_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='stopped',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
