# Generated by Django 5.0.2 on 2024-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0019_rename_game_date_gamemodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='referee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='round',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
