# Generated by Django 5.0.2 on 2024-02-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0020_gamemodel_referee_gamemodel_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='team_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Id по api'),
        ),
    ]
