# Generated by Django 5.0.2 on 2024-02-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0021_alter_teammodel_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplistmodel',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_top', to='sport.leaguemodel', unique=True),
        ),
        migrations.AlterField(
            model_name='toplistmodel',
            name='place',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Место'),
        ),
    ]
