# Generated by Django 5.0.2 on 2024-02-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0022_alter_toplistmodel_league_alter_toplistmodel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplistmodel',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_top', to='sport.leaguemodel'),
        ),
        migrations.AlterField(
            model_name='toplistmodel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='sport.teammodel', unique=True),
        ),
    ]
