# Generated by Django 5.0.2 on 2024-02-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0023_alter_toplistmodel_league_alter_toplistmodel_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='country',
        ),
    ]
