# Generated by Django 5.0.2 on 2024-02-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0024_remove_teammodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincolumnmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.countrymodel', verbose_name='country'),
        ),
    ]
