# Generated by Django 5.0.2 on 2024-02-19 16:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0025_maincolumnmodel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='Имя')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('telenumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграм')),
                ('whatsup', models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsUp')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('x', models.CharField(blank=True, max_length=255, null=True, verbose_name='X')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'Инфо',
            },
        ),
    ]
