# Generated by Django 5.0.2 on 2024-02-19 16:58

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0026_infomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.countrymodel'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Имя SEO'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='SEO Текст'),
        ),
    ]
