# Generated by Django 5.0.2 on 2024-02-21 09:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0029_infomodel_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='full_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полный SEO Текст'),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_league', to='sport.leaguemodel', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='national',
            field=models.BooleanField(default=False),
        ),
    ]
