# Generated by Django 5.0.2 on 2024-02-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0030_alter_infomodel_full_text_alter_seasonmodel_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='league',
            field=models.ManyToManyField(through='sport.TopListModel', to='sport.leaguemodel'),
        ),
        migrations.AlterField(
            model_name='toplistmodel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='sport.teammodel'),
        ),
    ]
