# Generated by Django 5.0.2 on 2024-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0032_alter_gamemodel_game_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplistmodel',
            name='draw',
            field=models.IntegerField(default=0, verbose_name='Ничья'),
        ),
        migrations.AddField(
            model_name='toplistmodel',
            name='lost',
            field=models.IntegerField(default=0, verbose_name='Поражение'),
        ),
        migrations.AddField(
            model_name='toplistmodel',
            name='win',
            field=models.IntegerField(default=0, verbose_name='Победы'),
        ),
    ]
