# Generated by Django 5.0.2 on 2024-02-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0033_toplistmodel_draw_toplistmodel_lost_toplistmodel_win'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toplistmodel',
            old_name='lost',
            new_name='lose',
        ),
    ]
