# Generated by Django 5.0.2 on 2024-02-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0038_alter_toplistmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toplistmodel',
            options={'ordering': ('-point',)},
        ),
    ]
