# Generated by Django 5.0.2 on 2024-02-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0039_alter_toplistmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='away_goals',
            field=models.IntegerField(blank=True, default=0, verbose_name='Гол (Гости)'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='home_goals',
            field=models.IntegerField(blank=True, default=0, verbose_name='Гол (Дома)'),
        ),
    ]
