# Generated by Django 5.0.2 on 2024-02-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0040_alter_gamemodel_away_goals_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguemodel',
            options={'ordering': ('games__date',), 'verbose_name': 'Лига', 'verbose_name_plural': 'Лиги'},
        ),
    ]
