# Generated by Django 5.0.2 on 2024-02-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0042_alter_leaguemodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='away_goals',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='home_goals',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='sport.toplistmodel', verbose_name='Гости'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='sport.toplistmodel', verbose_name='Дома'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='sport.toplistmodel', verbose_name='Победители'),
        ),
    ]
