# Generated by Django 5.0.2 on 2024-02-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0043_remove_gamemodel_away_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplistmodel',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Голы'),
        ),
    ]
