# Generated by Django 5.0.2 on 2024-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0044_toplistmodel_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='away_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='away_odds_old',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='away_odds_upper',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='draw_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='draw_odds_old',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='draw_odds_upper',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='home_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='home_odds_old',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='home_odds_upper',
            field=models.BooleanField(default=1),
        ),
    ]
