# Generated by Django 5.0.2 on 2024-02-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0046_alter_gamemodel_away_odds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplistmodel',
            name='forms',
            field=models.CharField(default='', max_length=255),
        ),
    ]
