# Generated by Django 5.0.2 on 2024-02-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0048_alter_toplistmodel_forms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toplistmodel',
            old_name='forms',
            new_name='form',
        ),
    ]
