# Generated by Django 5.0.2 on 2024-02-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0049_rename_forms_toplistmodel_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnmodel',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты'},
        ),
        migrations.AlterModelOptions(
            name='gamemodel',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='leaguemodel',
            options={'ordering': ('games__date',), 'verbose_name': 'Лига', 'verbose_name_plural': 'Лиги'},
        ),
        migrations.AlterModelOptions(
            name='maincolumnmodel',
            options={'verbose_name': 'Подвал', 'verbose_name_plural': 'Подвал'},
        ),
        migrations.AlterModelOptions(
            name='toplistmodel',
            options={'ordering': ('-point',), 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterField(
            model_name='toplistmodel',
            name='form',
            field=models.CharField(blank=True, default='?', max_length=6, null=True),
        ),
    ]
