# Generated by Django 5.0.2 on 2024-02-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0050_alter_columnmodel_options_alter_gamemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguemodel',
            name='country',
            field=models.ForeignKey(default=167, on_delete=django.db.models.deletion.CASCADE, to='sport.countrymodel', verbose_name='Страна'),
        ),
    ]
